### ISSUE TITLE
local execution fails

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#103]
with a "Submit job: communication error"

@FlanFlanagan, @yarden-livnat, any ideas?

**Comment by gidden** [comment]
note this may be related to #94 in that there is no "local" representation of a `CyclusJob`

**Comment by yarden-livnat** [comment]
I checked in a fix. 
I can't really check it because I don't have a local server but the bug was simple so this should fix it.

**Comment by gidden** [comment]
it is still broken for me. @yarden-livnat, would you mind using pull requests for this kind of update (i.e., those that you can't test locally)? that way, I can test the specific changes and we can discuss issues there as well.

**Comment by gidden** [comment]
I get the same issue as #109 here. my guess is that the failure is the same: the subroutine stops after the file fails to write

**Comment by gidden** [comment]
ok, I was working on an amalgamation of my PR branches, local execution works on the release branch. sorry for the false alarm!
